name: BirthdayPlugin
version: '${version}'
main: tw.brilliant.server.plugins.birthdayplugin.BirthdayPlugin
api-version: 1.19
authors: [ SiongSng ]
description: 輝煌伺服器的生日插件
website: brilliantw.net
commands:
  btd:
    usage: /btd <set/gs/at/gift/help>

depend: [PlaceholderAPI]